# GLOBAL EXTENSIONS

## Airflow Extentions
x-airflow-build: &airflow-build
  build:
    context: ./src/airflow
    dockerfile: Dockerfile
    args:
      - AIRFLOW_IMAGE_VERSION=2.11.0
      - JAVA_VERSION=17
      - JARS_DIRECTORY=/opt/airflow/jars
      - HADOOP_AWS_JAR_VERSION=3.3.4
      - MINIO_JAR_VERSION=8.5.17
      - POSTGRESQL_JAR_VERSION=42.7.8
      - AWS_BUNDLE_JAR_VERSION=1.12.782
  image: airflow_java:2.11.0-java17

x-airflow-env: &airflow-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_postgres/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@airflow_postgres/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://:@airflow_redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}

x-airflow-volumes: &airflow-volumes
    - ${AIRFLOW_PROJ_DIR:-./src/airflow}/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR:-./src/airflow}/logs:/opt/airflow/logs
    - ${AIRFLOW_PROJ_DIR:-./src/airflow}/config:/opt/airflow/config
    - ${AIRFLOW_PROJ_DIR:-./src/airflow}/plugins:/opt/airflow/plugins
    - ./generator:/opt/airflow/dags/generator

x-airflow-depends_on: &airflow-depends
    airflow_redis:
      condition: service_healthy
    airflow_postgres:
      condition: service_healthy

## Spark Extensions
x-spark-build: &spark-build
  build: 
      context: ./src/spark
      dockerfile: Dockerfile
      args:
        - SPARK_VERSION=4.0.1-scala2.13-java21-python3-r-ubuntu
        - JARS_DIRECTORY=/opt/spark/jars
        - HADOOP_AWS_JAR_VERSION=3.3.4
        - MINIO_JAR_VERSION=8.5.17
        - POSTGRESQL_JAR_VERSION=42.7.8
        - AWS_BUNDLE_JAR_VERSION=1.12.782
  image: spark_image:4.0.1

x-spark-env: &spark-env
    SPARK_RPC_AUTHENTICATION_ENABLED: 'no'
    SPARK_RPC_ENCRYPTION_ENABLED: 'no'
    SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: 'no'
    SPARK_SSL_ENABLED: 'no'
    SPARK_USER: 'spark'

services:

  ## Building Image

  airflow-build-image:
    <<: *airflow-build
    profiles: ["build"]
    command: ["echo", "Airflow image built"]

  spark-build-image:
    <<: *spark-build
    profiles: ["build"]
    command: ["echo", "Spark image built"]

  ## Postgres Data
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - dev-net
  
  ## Airflow Cluster
  airflow_postgres:
    image: postgres:17
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-airflow-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - dev-net

  airflow_redis:
    # Redis is limited to 7.2-bookworm due to licencing change
    # https://redis.io/blog/redis-adopts-dual-source-available-licensing/
    image: redis:7.2-bookworm
    container_name: airflow_redis
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always
    networks:
      - dev-net

  ### Airflow Base
  airflow-base: &airflow-base
    environment: *airflow-env
    image: airflow_java:2.11.0-java17
    volumes: *airflow-volumes
    user: "${AIRFLOW_UID:-50000}:0"
    depends_on: *airflow-depends
    networks:
      - dev-net

  airflow-webserver:
    <<: *airflow-base
    command: webserver
    container_name: airflow_webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-depends
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-base
    command: scheduler
    container_name: airflow_scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-depends
      airflow-init:
        condition: service_completed_successfully

  airflow-worker:
    <<: *airflow-base
    command: celery worker
    container_name: airflow_worker
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}" || celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      <<: *airflow-env
      DUMB_INIT_SETSID: "0"
    restart: always
    depends_on:
      <<: *airflow-depends
      airflow-init:
        condition: service_completed_successfully

  airflow-triggerer:
    <<: *airflow-base
    command: triggerer
    container_name: airflow_triggerer
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-depends
      airflow-init:
        condition: service_completed_successfully

  airflow-init:
    <<: *airflow-base
    entrypoint: /bin/bash
    command:
      - -c
      - |
        if [[ -z "${AIRFLOW_UID}" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
          echo "If you are on Linux, you SHOULD follow the instructions below to set "
          echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
          echo "For other operating systems you can get rid of the warning with manually created .env file:"
          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user"
          echo
        fi
        one_meg=1048576
        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
        disk_available=$$(df / | tail -1 | awk '{print $$4}')
        warning_resources="false"
        if (( mem_available < 4000 )) ; then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
          echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
          echo
          warning_resources="true"
        fi
        if (( cpus_available < 2 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
          echo "At least 2 CPUs recommended. You have $${cpus_available}"
          echo
          warning_resources="true"
        fi
        if (( disk_available < one_meg * 10 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
          echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
          echo
          warning_resources="true"
        fi
        if [[ $${warning_resources} == "true" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
          echo "Please follow the instructions to increase amount of resources available:"
          echo "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin"
          echo
        fi
        mkdir -p /sources/logs /sources/dags /sources/plugins /sources/jars
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version
    environment:
      <<: *airflow-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      _PIP_ADDITIONAL_REQUIREMENTS: ''
    user: "0:0"
    volumes:
      - ${AIRFLOW_PROJ_DIR:-./src/airflow}:/sources

  airflow-cli:
    <<: *airflow-base
    profiles:
      - debug
    environment:
      <<: *airflow-env
      CONNECTION_CHECK_MAX_COUNT: "0"
    # Workaround for entrypoint issue. See: https://github.com/apache/airflow/issues/16252
    command:
      - bash
      - -c
      - airflow

  # You can enable flower by adding "--profile flower" option e.g. docker-compose --profile flower up
  # or by explicitly targeted on the command line e.g. docker-compose up flower.
  # See: https://docs.docker.com/compose/profiles/
  flower:
    <<: *airflow-base
    command: celery flower
    container_name: airflow_flower
    profiles:
      - flower
    ports:
      - "5555:5555"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5555/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-depends
      airflow-init:
        condition: service_completed_successfully

  ## Minio Services
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
      - MINIO_DOMAIN=minio
    volumes:
      - minio_data:/data
    ports:
      - "9001:9001"
      - "9000:9000"
    entrypoint: >
      /bin/sh -c '
        isAlive() { curl -sf http://minio:9000/minio/health/live; }                                 # check if Minio is alive
        minio $0 "$@" --quiet & echo $! > /tmp/minio.pid                                            # start Minio in the background
        until isAlive; do sleep 1; done                                                             # wait until Minio is alive
        echo "MinIO is ready. Proceeding with setup..."
        mc alias set myminio http://minio:9000 admin admin123                                       # setup Minio client
        mc mb myminio/lake/ --ignore-existing                                                       # create test bucket
        mc anonymous set public myminio/lake                                                        # make the test bucket public
        mc admin accesskey create myminio admin --access-key admin_minio --secret-key admin_minio   # make the test bucket public
        kill -s INT $(cat /tmp/minio.pid) && rm /tmp/minio.pid                                      # stop Minio
        while isAlive; do sleep 0.1; done                                                           # wait until Minio is stopped
        exec minio $0 "$@"                                                                          # start Minio in the foreground
      '
    command: ["server", "/data", "--console-address", ":9001"]
    networks:
      - dev-net

  ## Superset Cluster
  superset:
    image: apache/superset:latest
    container_name: superset_app
    ports:
      - "8088:8088"
    environment:
      SUPERSET_WEBSERVER_LOG_LEVEL: "debug"
      SUPERSET_ENV: development
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_SECRET_KEY: "SupersetSecretKey"
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://superset:superset@superset_postgres:5432/superset
      REDIS_HOST: superset_redis
      REDIS_PORT: 6379
    volumes:
      - superset_home:/app/superset_home
    depends_on:
      - superset_postgres
      - superset_redis
    command: >
      /bin/bash -c "
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password superset_admin123 && 
        superset init &&
        superset run -h 0.0.0.0 -p 8088
      "
    networks:
      - dev-net

  superset_postgres:
    image: postgres:17
    container_name: superset_postgres
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
    volumes:
      - superset_postgres_data:/var/lib/postgresql/data
    networks:
      - dev-net

  superset_redis:
    image: redis:7.2-bookworm
    container_name: superset_redis
    networks:
      - dev-net

  ## Spark Cluster
  spark-master:
    image: spark_image:4.0.1
    container_name: spark-master
    hostname: spark-master
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master --host spark-master --webui-port 8080 --port 7077"
    environment:
      <<: *spark-env
      SPARK_MODE: 'master'
    ports:
      - "9090:8080"
      - "7077:7077"
    networks:
      - dev-net

  spark-worker-1:
    image: spark_image:4.0.1
    container_name: spark-worker-1
    hostname: spark-worker-1
    ports:
      - "9091:8081"
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker --webui-port 8081 spark://spark-master:7077"
    environment:
      <<: *spark-env
      SPARK_MODE: 'worker'
      SPARK_MASTER_URL: 'spark://spark-master:7077'
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: '2G'
      SPARK_DRIVER_MEMORY: '2G'
      SPARK_EXECUTOR_MEMORY: '2G'
    networks:
      - dev-net

volumes:
  postgres-airflow-volume:
  postgres-db-volume:
  minio_data:
  superset_postgres_data:
  superset_home:


networks:
  dev-net:
    driver: bridge